default_config:

homeassistant:
  packages: !include_dir_named packages/

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace: !include lovelace.yaml

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - http://localhost:4000/compass-card.js
