version: "3"
services:
  homeassistant:
    container_name: cc-homeassistant
    image: "ghcr.io/home-assistant/home-assistant:dev"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./ha/config:/config
      - ./ha/run:/etc/services.d/home-assistant/run
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - UMASK=007
      - PACKAGES=iputils  
    depends_on:
      - node       
  node:
    container_name: cc-node
    image: mcr.microsoft.com/devcontainers/typescript-node:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - TERM="xterm-256color"
    volumes:
      - ./:/home/node/app