resources:
  - url: http://127.0.0.1:5000/compass-card.js
    type: module
views:
  - cards:
      - type: custom:compass-card
        name: Compass Card Development
        entity: sun.sun
        test_gui: true
